config/routes.rb
Rails.application.routes.draw do
  resources :jobs, only: [:show, :new, :index]
  get '/about', to:'jobs#about', as: 'about'
  root to: 'jobs#index'
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def about
    
  end

  # GET /jobs
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  def show
    @renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to @job, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /jobs/1
  def update
    if @job.update(job_params)
      redirect_to @job, notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /jobs/1
  def destroy
    @job.destroy
    redirect_to jobs_url, notice: 'Job was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def job_params
      params[:job]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/jobs/_footer.html.erb
<div class="site-footer">
  <p><%= link_to "Home", jobs_path, class: 'footer_link' %> | <%= link_to "About", about_path, class: 'footer_link' %> | <%= link_to "Post", new_job_path, class: 'footer_link' %></p>
  <!-- <p><a href="#">Home</a> | <a href="#">Contact</a> | <a href="#">Submit</a>  </p> -->
</div>      

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/about.html.erb
<%= stylesheet_link_tag 'jobs/about', media: 'all', 'data-turbolinks-track' => true %>

<div class="post">
  <h4>About</h4>
  <p>This site is setup to serve both the iOS job seekers and recuiters in the Pacific Northwest. The site is sponsored and maintained by the lovely members of <%= link_to 'Seattle iOS Devs', 'http://www.meetup.com/Seattle-iOS-Developers/'%>.</p>

  <p>For any questions or for information on posting, please contact <%= link_to 'Taylor Halliday', 'mailto:taylor.halliday@gmail.com'%> or <%= link_to 'DJ Hayden', 'mailto:dj.hayden@stablekernel.com'%></p>

  <p><%= link_to 'Pull Requests Welcome :)', 'https://github.com/tayhalla/NWiOSJobs'%></p>
</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<% @jobs.each do |job| %>
  <div class="post">
    <h4><%= job.position_title %></h4>
    <p class="pull-right"><%= link_to 'Details', job, :class => "btn btn-danger" %></p>
    <!-- <p class="pull-right"><a href=<%= link_to job %>><span class="glyphicon glyphicon-log-out"></span></a></p> -->
    <h5><%= job.company %></h5>
    <small>Posted <%= time_ago_in_words(job.created_at) %> ago</small>
  </div>
<% end %>  

app/views/jobs/new.html.erb
<%= stylesheet_link_tag 'jobs/about', media: 'all', 'data-turbolinks-track' => true %>

<div class="post">
  <h4>Post A Job. It's Free!</h4>
  <h4>...for now...</h4>
  <p>If you are interested in posting a job, please contact <%= link_to 'Taylor Halliday', 'mailto:taylor.halliday@gmail.com'%>.</p> 
  <p>There will be a form here in the future (maybe this weekend)!</p>
  <p>This site is a work in progress.</p>
</div>

app/views/jobs/show.html.erb
<div class="post">
  <h4><%= @job.position_title %></h4>
  <h5><%= @job.company %></h5>
  
  <%= @renderer.render(@job.description).html_safe %>
  
  <p class='job_description'>Contact: <%= link_to @job.contact_name, 'mailto:#{@job.contact_name}'%></p></br>
  <small>Posted <%= time_ago_in_words(@job.created_at) %> ago</small>
</div>

<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <title>SeattleiOSJobs</title>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,400italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<!DOCTYPE html>
<body>
  <div class='content'> 
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 site">
          <div class="site-title">
            <h2><b>Northwest iOS Jobs</b></h2>
          </div>
          <%= yield %>
          <%= render 'footer' %>
        </div><!-- /col-md-6 -->
      </div>
    </div>
  </div>
</body>
</html>

<!-- Background js stuff -->
<script>$.backstretch("<%= asset_path 'forest_1.jpg' %>", {speed: 500});</script>

<!-- Analytics Baby -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54078423-1', 'auto');
  ga('send', 'pageview');

</script>